/* bp-fixture.js — a small but representative window.BP for testing the «Схема» engine before the real
 * assets/js/blueprint-data.js exists. Two graphs (overview, feature) covering every category, exec / data /
 * loop / fallback / blocked wires, reroute knots, comments, a composite drill-down (+ preset), instances,
 * ghost instances (×3), and scenarios with a par block. Schema: docs/design-skhema.md §12. */
window.BP = {
  schema: 1,
  pipelineVersion: '1.17.2',
  repoBlob: 'https://github.com/desvingns/mobile-pipeline/blob/main/',
  metrics: { COL: 336, LANE: 176, W: { full: 272, composite: 300, flow: 176, 'var': 208, tunnel: 208, compact: 272 },
    HEAD: 48, HEAD_FLOW: 30, ROW: 28, PAD_T: 8, PAD_B: 10, BANNER: 22, PIN_INSET: 14 },
  types: {
    exec: { ru: 'Выполнение', ue: 'Exec', color: '#FFFFFF' },
    Verdict: { ru: 'Вердикт pass/fail', ue: 'Boolean', color: '#C0282D' },
    Number: { ru: 'Число', ue: 'Integer', color: '#1EE0A5' },
    Route: { ru: 'Маршрут', ue: 'Enum', color: '#0F8A6A' },
    Idea: { ru: 'Идея / ответ человека', ue: 'Text', color: '#E27BA0' },
    SPEC: { ru: 'SPEC-блок', ue: 'String', color: '#F21FC9' },
    SpecBundle: { ru: 'Документ бандла', ue: 'Struct', color: '#2E6FE8' },
    Files: { ru: 'Файлы / дифф', ue: 'Object', color: '#19A7F0' },
    Report: { ru: 'JSON-отчёт скрипта', ue: 'Vector', color: '#F6C02B' },
    Findings: { ru: 'Замечания с ID', ue: 'Transform', color: '#F57A00' },
    Checklist: { ru: 'Чек-лист / матрица', ue: 'Name', color: '#C68BF5' },
    Screens: { ru: 'Скриншоты / эталоны', ue: 'Texture', color: '#A2E23A' },
    Memory: { ru: 'Урок / память', ue: 'Rotator', color: '#9EB1FF' },
    Proposal: { ru: 'Патч / PR', ue: 'Class', color: '#8B5CFF' }
  },
  cats: {
    EV: { ru: 'Событие', ue: 'Event' }, IN: { ru: 'Вход', ue: 'Entry' }, RT: { ru: 'Выход', ue: 'Return' },
    END: { ru: 'Стоп', ue: 'Terminal' }, AG: { ru: 'Агент', ue: 'Function' }, MS: { ru: 'Главная сессия', ue: 'Macro' },
    SC: { ru: 'Скрипт', ue: 'Library Function' }, PS: { ru: 'Чистый скрипт', ue: 'Pure Function' },
    HG: { ru: 'Человек', ue: 'Latent Macro' }, BR: { ru: 'Ветвление', ue: 'Branch' }, SW: { ru: 'Выбор', ue: 'Switch' },
    PA: { ru: 'Параллельно', ue: 'Parallel' }, JN: { ru: 'Слияние', ue: 'Join' }, VA: { ru: 'Артефакт', ue: 'Variable' },
    CP: { ru: 'Составной граф', ue: 'Collapsed Graph' }, CL: { ru: 'Группа', ue: 'Collapsed Nodes' }, PR: { ru: 'Подсказка', ue: 'Print String' }
  },
  defs: {
    'mp-planner': { cat: 'AG', title: '/mp --plan: разложить на SPEC', tech: 'mp-planner', model: { tier: 'sonnet', id: 'claude-sonnet-4-6' },
      tools: ['Read', 'Write', 'Glob', 'Grep'], src: ['templates/common/agents/{{PREFIX}}-planner.md'], codex: 'subagent-toml',
      pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'idea', t: 'Idea', l: 'бандл / идея' }], out: [{ id: 'then', t: 'exec' }, { id: 'specs', t: 'SPEC', l: 'SPEC эпика', arr: true }] },
      d: { what: 'Режет принятый бандл на карточки SPEC размером в один вечер работы. Каждая карточка получает критерии приёмки и ссылки на требования FR-NNN. Ничего не пишет в код.', stops: 'Если бандл противоречив — останавливается и перечисляет конфликтующие требования.', order: 'После /mp-spec, перед гейтом записи.' },
      sample: '{"specs":["SPEC-07 reminder-notification","SPEC-08 watering-calendar"],"count":2}' },
    'mp-developer-android': { cat: 'AG', title: 'Разработчик (мощный)', tech: 'mp-developer-android', model: { tier: 'opus', id: 'claude-opus-4-8' },
      tools: ['Bash', 'Read', 'Write', 'Edit', 'Glob', 'Grep'], flags: ['commits'],
      src: ['templates/android/agents/{{PREFIX}}-developer-android.md'], also: ['templates/common/commands/runtime/contract-feature-implementation.md'], codex: 'subagent-toml',
      pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }, { id: 'tokens', t: 'Report', l: 'DESIGN_TOKENS' }, { id: 'facts', t: 'Files', l: 'факты разведки', arr: true }],
        out: [{ id: 'then', t: 'exec' }, { id: 'files', t: 'Files', l: 'changed_files + commit', arr: true }] },
      d: { what: 'Пишет код задачи по SPEC и матрице приёмки, соблюдая слои Clean Architecture. Делает один коммит на задачу. Тесты не запускает — это делает runner-android.sh.', stops: 'Останавливается, если SPEC требует решения по архитектуре, которого нет в капсуле.', order: 'Строго после маршрута риска; выбирается, если developer_tier = powerful.' },
      sample: '{"changed_files":["domain/reminder/WateringReminderScheduler.kt"],"commit":"3f9c2e1"}' },
    'grounding-scout': { cat: 'AG', title: 'Разведка кода ×3', tech: 'grounding-scout', model: { tier: 'haiku', id: 'claude-haiku-4-5' },
      tools: ['Read', 'Glob', 'Grep'], flags: ['readonly'], src: ['templates/spec/agents/grounding-scout.md'],
      pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }], out: [{ id: 'then', t: 'exec' }, { id: 'facts', t: 'Files', l: 'факты кода', arr: true }] },
      d: { what: 'Читает готовый проект и возвращает факты: где лежат экраны, как устроены репозитории, какие есть шаблоны. До трёх разведчиков работают одновременно.', stops: 'Только читает (по контракту).', order: 'Параллельно, до 3 экземпляров.' } },
    'mp-risk-route.sh': { cat: 'SC', title: 'Маршрут риска', tech: 'mp-risk-route.sh', src: ['templates/android/scripts/{{PREFIX}}-risk-route.sh'],
      pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }], out: [{ id: 'then', t: 'exec' }, { id: 'route', t: 'Route', l: 'developer_tier' }, { id: 'report', t: 'Report', l: 'JSON' }] },
      d: { what: 'Считает риск задачи по правилам и выбирает разработчика и количество проверок. Одинаковый вход всегда даёт одинаковый ответ.' },
      sample: '{"risk":"low","developer_tier":"standard","semantic_review":false,"verifier":"full","independent_critic":false}' }
  },
  graphs: [
    {
      id: 'overview', tab: 'Обзор', title: 'Обзор конвейера', entry: 'ev-start',
      desc: 'Весь путь от идеи до выпуска: требования, план, реализация и самообучение. Составные ноды открываются двойным щелчком.',
      nodes: [
        { id: 'ev-start', cat: 'EV', title: 'Старт: идея или чужое приложение', tech: 'человек', at: [0, 1],
          pins: { out: [{ id: 'then', t: 'exec' }, { id: 'idea', t: 'Idea', l: 'идея' }, { id: 'screens', t: 'Screens', l: 'скриншоты', arr: true }] },
          d: { what: 'Всё начинается с человека: фраза с идеей или снимки чужого приложения. Отсюда конвейер решает, какой режим запускать.' } },
        { id: 'sw-intake', cat: 'SW', title: 'Что есть на входе?', tech: 'Switch on Intake', at: [0.95, 1.1],
          pins: { 'in': [{ id: 'in', t: 'exec' }], out: [{ id: 'clone', t: 'exec', l: 'клон' }, { id: 'green', t: 'exec', l: 'с нуля' }] } },
        { id: 'fn-plan', def: 'mp-planner', at: [1.75, 0.9] },
        { id: 'g-plan', cat: 'HG', title: 'Записать N SPEC? (y/d/n)', tech: 'gate · /mp --plan', gate: 'always', at: [2.6, 0.9],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'specs', t: 'SPEC', l: 'SPEC', arr: true }], out: [{ id: 'y', t: 'exec', l: 'y' }, { id: 'n', t: 'exec', l: 'n' }, { id: 'specs', t: 'SPEC', l: 'SPEC', arr: true }] },
          d: { what: 'Человек смотрит список карточек и отвечает y, d (подробнее) или n. Без ответа ничего не записывается на доску.', human: 'Всегда ждёт' } },
        { id: 'var-board', cat: 'VA', set: true, multiIn: true, title: 'Доска: backlog → active → done', tech: '.claude/specs/', at: [3.45, 2.1],
          pins: { 'in': [{ id: 'in', t: 'SPEC', arr: true, l: 'SPEC' }], out: [{ id: 'out', t: 'SPEC', arr: true, l: 'SPEC' }] } },
        { id: 'cp-feature', cat: 'CP', opens: 'feature', title: '/mp --feature --next', tech: '/mp --feature', at: [4.35, 0.9],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'specs', t: 'SPEC', l: 'SPEC', arr: true }], out: [{ id: 'then', t: 'exec' }, { id: 'files', t: 'Files', l: 'коммит', arr: true }] },
          d: { what: 'Берёт верхнюю карточку с доски и проводит её через всю цепочку: размер, маршрут, код, ревью, тесты, проверку и пуш.' } },
        { id: 'var-app', cat: 'VA', set: true, multiIn: true, title: 'Приложение', tech: 'Kotlin · Compose · Hilt · Room', at: [5.35, 2.1],
          pins: { 'in': [{ id: 'in', t: 'Files', arr: true }], out: [{ id: 'out', t: 'Files', arr: true }] } },
        { id: 'var-refs', cat: 'VA', title: 'Эталоны клона', tech: 'spec/fit/', at: [5.35, -0.5],
          pins: { out: [{ id: 'out', t: 'Screens', arr: true }] } },
        { id: 'fn-fit', cat: 'AG', title: '/mp --fit: сверка с оригиналом', tech: 'mp-fit-android', model: { tier: 'opus', id: 'claude-opus-4-7' }, cond: 'только клон', at: [6.2, 0.2],
          tools: ['Bash', 'Read', 'Glob'], src: ['templates/android/agents/{{PREFIX}}-fit-android.md', 'templates/android/scripts/pixel-diff.sh'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'build', t: 'Files', l: 'сборка', arr: true }, { id: 'refs', t: 'Screens', l: 'эталоны', arr: true }],
            out: [{ id: 'ok', t: 'exec', l: 'похоже' }, { id: 'diff', t: 'exec', l: 'расхождения' }, { id: 'specs', t: 'SPEC', l: 'новые SPEC', arr: true }, { id: 'score', t: 'Number', l: 'похожесть' }] },
          d: { what: 'Сравнивает экраны собранного приложения с эталонами. Если похожесть ниже 85 из 100 — пишет карточки расхождений обратно на доску.' } },
        { id: 'cp-learn', cat: 'CL', title: 'Самообучение', tech: 'post-ship · --improve · --reflect', at: [6.2, 1.6],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'files', t: 'Files', arr: true, l: 'коммит' }], out: [{ id: 'then', t: 'exec' }, { id: 'pr', t: 'Proposal', l: 'PR' }] },
          d: { what: 'Свёрнутая группа: оценка, уроки и предложения по улучшению самого конвейера.', internals: ['mp-knowledge', 'mp-improve', 'mp-reflect', 'mp-record-run.sh'] } },
        { id: 'var-repo', cat: 'VA', set: true, title: 'mobile-pipeline: templates/', tech: 'github.com/desvingns/mobile-pipeline', at: [7.2, 1.75],
          pins: { 'in': [{ id: 'in', t: 'Proposal' }], out: [{ id: 'templates', t: 'Files', arr: true, l: 'templates/' }] } },
        { id: 'ev-install', cat: 'EV', title: 'Установка (раз на проект)', tech: '/plugin install · bootstrap.sh', at: [0, 3.4],
          pins: { out: [{ id: 'then', t: 'exec' }] } },
        { id: 'sc-install', cat: 'SC', title: 'Сгенерировать конвейер в проект', tech: 'bootstrap.sh', at: [0.95, 3.4], src: ['bootstrap.sh', 'install-spec.sh'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'templates', t: 'Files', arr: true, l: 'templates/' }], out: [{ id: 'then', t: 'exec' }, { id: 'route', t: 'Route', l: 'Claude | Codex' }] } },
        { id: 'm-bugfix', cat: 'CL', compact: true, title: '--bugfix: починить ошибку', tech: 'preset bugfix', opens: 'feature', preset: 'bugfix', at: [2.2, 3.4] },
        { id: 'm-discuss', cat: 'CL', compact: true, title: '--discuss: обсудить идею', tech: 'mp-architect · BRAINSTORM', at: [2.2, 3.72] },
        { id: 'm-device', cat: 'CL', compact: true, title: '--device: на телефоне', tech: 'mp-runner-instrumented-android', at: [3.1, 3.4] },
        { id: 'm-coverage', cat: 'CL', compact: true, title: '--coverage: покрытие', tech: 'mp-coverage-android · haiku', at: [3.1, 3.72] }
      ],
      wires: [
        'ev-start.then>sw-intake.in',
        'sw-intake.clone>fn-plan.in',
        'sw-intake.green>fn-plan.in',
        'fn-plan.then>g-plan.in',
        'g-plan.y>cp-feature.in',
        'cp-feature.then>fn-fit.in',
        'fn-fit.ok>cp-learn.in',
        { f: 'fn-fit.diff', t: 'cp-feature.in', k: 'loop', via: [[7.0, -1.2], [4.2, -1.2]], badge: 'расхождения → новые SPEC' },
        'ev-install.then>sc-install.in',
        'ev-start.idea>fn-plan.idea',
        'fn-plan.specs>g-plan.specs',
        'g-plan.specs>var-board.in',
        'var-board.out>cp-feature.specs',
        'cp-feature.files>var-app.in',
        'var-app.out>fn-fit.build',
        'var-refs.out>fn-fit.refs',
        { f: 'fn-fit.specs', t: 'var-board.in', k: 'loop', via: [[7.0, 2.8], [3.3, 2.8]] },
        'cp-feature.files>cp-learn.files',
        'cp-learn.pr>var-repo.in',
        { f: 'var-repo.templates', t: 'sc-install.templates', k: 'loop', via: [[7.9, 4.5], [0.6, 4.5]], badge: 'новая версия → все проекты' }
      ],
      comments: [
        { id: 'c-plan', key: 1, title: '1 · План', color: '#2aa198', nodes: ['fn-plan', 'g-plan', 'var-board'], d: 'Бандл режется на карточки SPEC; человек подтверждает запись на доску.' },
        { id: 'c-build', key: 2, title: '2 · Реализация и сверка', color: '#3f9d4a', nodes: ['cp-feature', 'var-app', 'var-refs', 'fn-fit', 'cp-learn', 'var-repo'], d: 'Каждая карточка проходит цепочку /mp --feature; клон дополнительно сверяется с оригиналом.' },
        { id: 'c-install', key: 0, title: '0 · Установка', color: '#6b7280', nodes: ['ev-install', 'sc-install'] },
        { id: 'c-modes', title: 'Остальные режимы /mp', color: '#58657a', nodes: ['m-bugfix', 'm-discuss', 'm-device', 'm-coverage'] }
      ]
    },
    {
      id: 'feature', tab: '/mp --feature', title: '/mp --feature', parent: 'overview', entry: 'in-feature',
      desc: 'Одна карточка SPEC от доски до пуша. Цепочка строго последовательная, кроме разведки.',
      nodes: [
        { id: 'in-feature', cat: 'IN', title: 'Вход: --feature --next', tech: 'contract-feature.md', at: [0, 2.2],
          pins: { out: [{ id: 'then', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC (active/)' }] } },
        { id: 'sc-size', cat: 'SC', title: 'Размер: ячейки матрицы', tech: 'mp-spec-complexity.sh', at: [0.9, 2.2], src: ['templates/android/scripts/{{PREFIX}}-spec-complexity.sh'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }], out: [{ id: 'ok', t: 'exec', l: 'ok' }, { id: 'split', t: 'exec', l: 'split' }, { id: 'report', t: 'Report', l: 'JSON' }, { id: 'matrix', t: 'Checklist', l: 'матрица', arr: true }] },
          d: { what: 'Считает ячейки матрицы приёмки. Слишком большая задача уходит на разделение.' },
          sample: '{"cells":4,"limit":12,"verdict":"ok"}' },
        { id: 'g-size', cat: 'HG', title: 'Разделить на SPEC-и? (Y/n)', tech: 'gate · size', gate: 'unattended', at: [1.9, 0.45],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'report', t: 'Report', l: 'JSON' }], out: [{ id: 'n', t: 'exec', l: 'n' }, { id: 'Y', t: 'exec', l: 'Y' }] } },
        { id: 'end-split', cat: 'END', title: 'Вернуть планировщику', tech: 'stop · split', at: [2.85, 0.45], pins: { 'in': [{ id: 'in', t: 'exec' }] } },
        { id: 'par-a', cat: 'PA', title: 'Параллельно ×2', at: [3.95, 2.25],
          pins: { 'in': [{ id: 'in', t: 'exec' }], out: [{ id: '0', t: 'exec', l: 'разведка' }, { id: '1', t: 'exec', l: 'тема' }] } },
        { id: 'fn-scout', def: 'grounding-scout', instances: 3, at: [4.75, 1.3] },
        { id: 'fn-ui', cat: 'AG', title: 'Токены темы Material 3', tech: 'mp-ui-designer-android', model: { tier: 'sonnet', id: 'claude-sonnet-4-6' }, cond: 'LAYERS ∋ presentation', at: [4.75, 2.75],
          tools: ['Read', 'Write', 'Edit'], src: ['templates/android/agents/{{PREFIX}}-ui-designer-android.md'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }], out: [{ id: 'then', t: 'exec' }, { id: 'tokens', t: 'Report', l: 'DESIGN_TOKENS' }] } },
        { id: 'join-a', cat: 'JN', title: 'Дождаться обоих', at: [5.75, 2.25],
          pins: { 'in': [{ id: '0', t: 'exec', l: '1' }, { id: '1', t: 'exec', l: '2' }], out: [{ id: 'then', t: 'exec' }] } },
        { id: 'var-spec', cat: 'VA', title: 'SPEC (active/)', tech: '.claude/specs/active/', at: [5.75, 3.75], pins: { out: [{ id: 'spec', t: 'SPEC', l: 'SPEC' }] } },
        { id: 'fn-dev', def: 'mp-developer-android', at: [6.45, 2.2] },
        { id: 'var-diff', cat: 'VA', set: true, multiIn: true, title: 'CHANGED_FILES', tech: 'git diff --name-only', at: [6.9, 3.8],
          pins: { 'in': [{ id: 'in', t: 'Files', arr: true }], out: [{ id: 'out', t: 'Files', arr: true }] } },
        { id: 'sc-review', cat: 'SC', title: 'Границы слоёв (Clean Arch.)', tech: 'mp-reviewer-android.sh', at: [7.55, 2.2], src: ['templates/android/scripts/{{PREFIX}}-reviewer-android.sh'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'files', t: 'Files', arr: true, l: 'CHANGED_FILES' }], out: [{ id: 'pass', t: 'exec', l: 'pass' }, { id: 'fail', t: 'exec', l: 'fail' }, { id: 'crash', t: 'exec', l: 'crash' }] } },
        { id: 'fn-review-fb', cat: 'AG', title: 'Запасной ревьюер', tech: 'mp-reviewer-android', model: { tier: 'haiku', id: 'claude-haiku-4-5' }, fallback: true, at: [7.55, 0.7],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'files', t: 'Files', arr: true, l: 'CHANGED_FILES' }], out: [{ id: 'pass', t: 'exec', l: 'pass' }, { id: 'fail', t: 'exec', l: 'fail' }] } },
        { id: 'end-review', cat: 'END', title: 'Стоп: показать нарушения', at: [8.5, -0.35], pins: { 'in': [{ id: 'in', t: 'exec' }] } },
        { id: 'sc-run', cat: 'SC', title: 'Прогон: scoped → full', tech: 'mp-runner-android.sh', at: [9.6, 2.2], src: ['templates/android/scripts/{{PREFIX}}-runner-android.sh'],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'tests', t: 'Files', arr: true, l: 'тесты' }], out: [{ id: 'pass', t: 'exec', l: 'pass' }, { id: 'fail', t: 'exec', l: 'fail' }, { id: 'report', t: 'Report', l: 'JSON' }] },
          d: { what: 'Запускает тесты, detekt, lint и покрытие. Сначала только затронутые тесты, потом полный прогон.' } },
        { id: 'br-fixed', cat: 'BR', title: 'Автопочинка уже была?', at: [10.55, 3.4],
          pins: { 'in': [{ id: 'in', t: 'exec' }], out: [{ id: 'no', t: 'exec', l: 'нет' }, { id: 'yes', t: 'exec', l: 'да' }] } },
        { id: 'fn-dev@fix', title: 'Одна автопочинка, без новой логики', at: [11.35, 3.4] },
        { id: 'end-run', cat: 'END', title: 'Стоп: два отчёта, спросить', at: [11.35, 4.65], pins: { 'in': [{ id: 'in', t: 'exec' }] } },
        { id: 'g-push', cat: 'HG', title: 'Готово к пушу? (y/N)', tech: 'gate · push', gate: 'hard', at: [12.45, 2.2],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'checklist', t: 'Checklist', l: 'чек-лист', arr: true }], out: [{ id: 'y', t: 'exec', l: 'y' }, { id: 'N', t: 'exec', l: 'N' }] },
          d: { what: 'Жёсткая остановка: без явного «y» от человека пуша не будет, даже в режиме --unattended.', human: 'HARD STOP' } },
        { id: 'ms-docs', cat: 'MS', title: 'STATE / DOCUMENTATION', tech: 'mp-docs · inline', at: [13.45, 2.2],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'files', t: 'Files', arr: true, l: 'коммит' }], out: [{ id: 'then', t: 'exec' }] } },
        { id: 'set-lessons', cat: 'VA', set: true, title: 'lessons.md (+1 строка)', tech: '.claude/memory/lessons.md', at: [14.45, 1.25],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'lesson', t: 'Memory', l: 'урок' }], out: [{ id: 'then', t: 'exec' }, { id: 'out', t: 'Memory', l: 'урок' }] } },
        { id: 'ps-brain', cat: 'PS', title: 'В inbox «второго мозга»', tech: 'mp-brain-memory.sh', at: [14.45, 2.9],
          pins: { 'in': [{ id: 'lesson', t: 'Memory', l: 'урок' }], out: [{ id: 'cand', t: 'Memory', l: 'кандидат' }] } },
        { id: 'pr-nudge', cat: 'PR', title: 'Подсказка: /mp --improve --drain', tech: 'print', at: [15.45, 1.3],
          pins: { 'in': [{ id: 'in', t: 'exec' }], out: [{ id: 'then', t: 'exec' }] } },
        { id: 'out-done', cat: 'RT', title: 'SPEC → done/ · отчёт', tech: 'contract-post-ship.md', at: [16.4, 2.2],
          pins: { 'in': [{ id: 'in', t: 'exec' }, { id: 'spec', t: 'SPEC', l: 'SPEC' }] } }
      ],
      wires: [
        'in-feature.then>sc-size.in',
        'sc-size.ok>par-a.in',
        'sc-size.split>g-size.in',
        'g-size.n>par-a.in',
        'g-size.Y>end-split.in',
        'par-a.0>fn-scout.in',
        'par-a.1>fn-ui.in',
        'fn-scout.then>join-a.0',
        'fn-ui.then>join-a.1',
        'join-a.then>fn-dev.in',
        'fn-dev.then>sc-review.in',
        'sc-review.pass>sc-run.in',
        'sc-review.fail>end-review.in',
        { f: 'sc-review.crash', t: 'fn-review-fb.in', k: 'fallback' },
        'fn-review-fb.pass>sc-run.in',
        'fn-review-fb.fail>end-review.in',
        'sc-run.pass>g-push.in',
        'sc-run.fail>br-fixed.in',
        'br-fixed.no>fn-dev@fix.in',
        { f: 'br-fixed.yes', t: 'end-run.in', k: 'blocked' },
        { f: 'fn-dev@fix.then', t: 'sc-run.in', k: 'loop', via: [[12.2, 5.3], [9.35, 5.3]], badge: '1 попытка' },
        'g-push.y>ms-docs.in',
        'ms-docs.then>set-lessons.in',
        'set-lessons.then>pr-nudge.in',
        'pr-nudge.then>out-done.in',
        'in-feature.spec>sc-size.spec',
        'in-feature.spec>fn-scout.spec',
        'in-feature.spec>fn-ui.spec',
        'sc-size.report>g-size.report',
        'sc-size.matrix>g-push.checklist',
        'var-spec.spec>fn-dev.spec',
        'fn-ui.tokens>fn-dev.tokens',
        'fn-scout.facts>fn-dev.facts',
        'fn-dev.files>var-diff.in',
        'fn-dev@fix.files>var-diff.in',
        'var-diff.out>sc-review.files',
        'var-diff.out>fn-review-fb.files',
        'var-diff.out>sc-run.tests',
        'var-diff.out>ms-docs.files',
        'set-lessons.out>ps-brain.lesson',
        'var-spec.spec>out-done.spec'
      ],
      comments: [
        { id: 'c-take', key: 1, title: '1 · Взять задачу', color: '#2aa198', nodes: ['sc-size', 'g-size', 'end-split'] },
        { id: 'c-impl', key: 2, title: '2 · Разведка и реализация', color: '#3f9d4a', nodes: ['par-a', 'fn-scout', 'fn-ui', 'join-a', 'fn-dev', 'var-spec', 'var-diff'] },
        { id: 'c-review', key: 3, title: '3 · Ревью', color: '#d9822b', nodes: ['sc-review', 'fn-review-fb', 'end-review'] },
        { id: 'c-tests', key: 4, title: '4 · Тесты и автопочинка', color: '#5aa9e6', nodes: ['sc-run', 'br-fixed', 'fn-dev@fix', 'end-run'], d: 'Одна автопочинка после упавших тестов, потом — стоп и вопрос человеку.' },
        { id: 'c-close', key: 5, title: '5 · Пуш и закрытие', color: '#8e6bd8', nodes: ['g-push', 'ms-docs', 'set-lessons', 'ps-brain', 'pr-nudge'] }
      ]
    }
  ],
  presets: {
    bugfix: { graph: 'feature', title: '--bugfix', banner: 'Режим --bugfix: перед цепочкой — g-repro; после прогона — перепроверка на телефоне; верификатор может быть lite.', highlight: ['sc-run', 'fn-dev', 'g-push'] }
  },
  scenarios: {
    feature: [
      { id: 'ft-autofix', title: 'Тесты упали → одна автопочинка', steps: [
        { n: 'in-feature', st: 'ok', tag: 'LogBlueprint', text: 'SPEC-07 «Напоминание о поливе» → active/' },
        { w: 'in-feature.then>sc-size.in', n: 'sc-size', out: 'ok', st: 'ok', data: ['in-feature.spec>sc-size.spec'], json: { cells: 4, limit: 12, verdict: 'ok' } },
        { w: 'sc-size.ok>par-a.in', n: 'par-a', st: 'ok' },
        { par: [
          [{ w: 'par-a.0>fn-scout.in', n: 'fn-scout', st: 'ok', data: ['in-feature.spec>fn-scout.spec'], json: { facts: ['ui/plants/PlantListScreen.kt', 'data/reminder/ReminderRepository.kt'] } },
           { w: 'fn-scout.then>join-a.0', n: 'join-a', st: 'ok' }],
          [{ w: 'par-a.1>fn-ui.in', n: 'fn-ui', st: 'skip', text: 'LAYERS не содержит presentation — пропущено' }]
        ] },
        { w: 'join-a.then>fn-dev.in', n: 'fn-dev', st: 'ok', data: ['fn-scout.facts>fn-dev.facts', 'var-spec.spec>fn-dev.spec'], json: { changed_files: ['domain/reminder/WateringReminderScheduler.kt'], commit: '8a41d07' } },
        { w: 'fn-dev.then>sc-review.in', n: 'sc-review', out: 'pass', st: 'ok', data: ['fn-dev.files>var-diff.in', 'var-diff.out>sc-review.files'], json: { pass: true, violations: 0 } },
        { w: 'sc-review.pass>sc-run.in', n: 'sc-run', out: 'fail', st: 'fail', lvl: 'error', data: ['var-diff.out>sc-run.tests'],
          json: { pass: false, mode: 'full', tests: '40 passed / 2 failed', detekt: 'ok', lint: 'ok', coverage: '71%', errors: ['WateringReminderSchedulerTest > fires at 09:00 local time FAILED'] }, live: 'runner-android.sh: тесты упали' },
        { w: 'sc-run.fail>br-fixed.in', n: 'br-fixed', out: 'нет', st: 'ok', text: 'автопочинки ещё не было → нет' },
        { w: 'br-fixed.no>fn-dev@fix.in', n: 'fn-dev@fix', st: 'ok', json: { changed_files: ['domain/reminder/WateringReminderScheduler.kt'], commit: 'c41e9b2', note: 'ZoneId.systemDefault()' } },
        { w: 'fn-dev@fix.then>sc-run.in', n: 'sc-run', out: 'pass', st: 'ok', counter: { node: 'fn-dev@fix', text: 'попытка 1/1' }, json: { pass: true, mode: 'full', tests: '42 passed', coverage: '72%' } },
        { w: 'sc-run.pass>g-push.in', n: 'g-push', st: 'wait', answer: 'y', lvl: 'warning', data: ['sc-size.matrix>g-push.checklist'], text: 'g-push ждёт человека: «Готово к пушу? (y/N)» → y' },
        { w: 'g-push.y>ms-docs.in', n: 'ms-docs', st: 'ok', data: ['var-diff.out>ms-docs.files'], text: 'STATE.md, DOCUMENTATION.md обновлены' },
        { w: 'ms-docs.then>set-lessons.in', n: 'set-lessons', st: 'ok', text: '+1 урок: время уведомлений — только в локальной зоне' },
        { w: 'set-lessons.then>pr-nudge.in', n: 'pr-nudge', st: 'ok', text: 'Подсказка: /mp --improve --drain' },
        { w: 'pr-nudge.then>out-done.in', n: 'out-done', st: 'ok', data: ['var-spec.spec>out-done.spec'], text: 'SPEC-07 → done/' }
      ] },
      { id: 'ft-review-crash', title: 'Скрипт ревью упал → запасной ревьюер', steps: [
        { n: 'in-feature', st: 'ok' },
        { w: 'in-feature.then>sc-size.in', n: 'sc-size', out: 'split', st: 'warn', lvl: 'warning', json: { cells: 15, limit: 12, verdict: 'split' } },
        { w: 'sc-size.split>g-size.in', n: 'g-size', st: 'wait', answer: 'n', text: '--unattended: авто Y не сработал, человек ответил n' },
        { w: 'g-size.n>par-a.in', n: 'par-a', st: 'ok' },
        { par: [[{ w: 'par-a.0>fn-scout.in', n: 'fn-scout', st: 'ok' }, { w: 'fn-scout.then>join-a.0', n: 'join-a', st: 'ok' }], [{ w: 'par-a.1>fn-ui.in', n: 'fn-ui', st: 'ok', json: { tokens: 'theme/Color.kt' } }]] },
        { w: 'join-a.then>fn-dev.in', n: 'fn-dev', st: 'ok' },
        { w: 'fn-dev.then>sc-review.in', n: 'sc-review', out: 'crash', st: 'fail', lvl: 'error', text: 'mp-reviewer-android.sh: exit 2 (crash)' },
        { w: 'sc-review.crash>fn-review-fb.in', n: 'fn-review-fb', out: 'pass', st: 'ok', json: { pass: true, via: 'fallback' } },
        { w: 'fn-review-fb.pass>sc-run.in', n: 'sc-run', out: 'pass', st: 'ok' }
      ] }
    ],
    overview: [
      { id: 'ov-plan', title: 'Идея → план → реализация', steps: [
        { n: 'ev-start', st: 'ok', text: '«Полей меня»: напоминать о поливе' },
        { w: 'ev-start.then>sw-intake.in', n: 'sw-intake', out: 'с нуля', st: 'ok' },
        { w: 'sw-intake.green>fn-plan.in', n: 'fn-plan', st: 'ok', data: ['ev-start.idea>fn-plan.idea'], json: { specs: ['SPEC-07', 'SPEC-08'], count: 2 } },
        { w: 'fn-plan.then>g-plan.in', n: 'g-plan', st: 'wait', answer: 'y', data: ['fn-plan.specs>g-plan.specs'], lvl: 'warning', text: 'g-plan ждёт человека: «Записать 2 SPEC?» → y' },
        { w: 'g-plan.y>cp-feature.in', n: 'cp-feature', st: 'ok', data: ['g-plan.specs>var-board.in', 'var-board.out>cp-feature.specs'], json: { spec: 'SPEC-07', commit: '8a41d07' } },
        { w: 'cp-feature.then>fn-fit.in', n: 'fn-fit', out: 'расхождения', st: 'warn', lvl: 'warning', data: ['cp-feature.files>var-app.in', 'var-app.out>fn-fit.build', 'var-refs.out>fn-fit.refs'], json: { similarity: 78, threshold: 85, new_specs: 2 } },
        { w: 'fn-fit.diff>cp-feature.in', n: 'cp-feature', st: 'ok', data: ['fn-fit.specs>var-board.in'], text: '2 SPEC расхождений → снова /mp --feature' }
      ] }
    ]
  }
};
