#!/usr/bin/env node
// Regenerates assets/css/fonts.css with the woff2 files inlined as base64 data URIs.
// Why inline: Firefox treats every file:// URL as its own origin and blocks @font-face
// loads, so fonts must travel inside the stylesheet for double-click opening to work.
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const fontsDir = path.join(root, 'assets', 'fonts');
const out = path.join(root, 'assets', 'css', 'fonts.css');

const CYR = 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116';
const LAT = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';

const families = [
  { family: 'Unbounded', file: 'unbounded', weight: '200 900' },
  { family: 'Golos Text', file: 'golos-text', weight: '400 900' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono', weight: '100 800' },
];

let css = '/* Generated by tools/build-fonts.cjs — do not edit by hand. Fonts: OFL-1.1, see assets/fonts/LICENSE-*.txt */\n';
for (const f of families) {
  for (const [subset, range] of [['cyrillic', CYR], ['latin', LAT]]) {
    const file = path.join(fontsDir, `${f.file}-${subset}-wght-normal.woff2`);
    const b64 = fs.readFileSync(file).toString('base64');
    css += `@font-face{font-family:'${f.family}';font-style:normal;font-display:swap;font-weight:${f.weight};` +
      `src:url(data:font/woff2;base64,${b64}) format('woff2');unicode-range:${range};}\n`;
  }
}
fs.writeFileSync(out, css);
console.log(`fonts.css written: ${(css.length / 1024).toFixed(1)} KB`);
