/* Generated by video/scripts/build-video.cjs; duration refreshed by verify-output.cjs from the render. */
window.MP_VIDEO = {
 "duration": 178.9,
 "chapters": [
  {
   "id": "s01-hook",
   "title": "Фиалка поникла",
   "start": 0
  },
  {
   "id": "s02-factory",
   "title": "Фабрика",
   "start": 15.7
  },
  {
   "id": "s03-talk",
   "title": "Разговор",
   "start": 32.3
  },
  {
   "id": "s04-blueprint",
   "title": "Чертёж",
   "start": 50.7
  },
  {
   "id": "s05-critic",
   "title": "Придира",
   "start": 65.7
  },
  {
   "id": "s06-plan",
   "title": "План",
   "start": 77.1
  },
  {
   "id": "s07-belt",
   "title": "Конвейер",
   "start": 91.8
  },
  {
   "id": "s08-tests",
   "title": "Испытания",
   "start": 113.8
  },
  {
   "id": "s09-release",
   "title": "Выпуск",
   "start": 137.4
  },
  {
   "id": "s10-memory",
   "title": "Память",
   "start": 157.5
  }
 ]
};
